services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pendura-ai-api:
    image: jorgeroniel07/pendura-ai-server:0.0.6
    container_name: pendura-ai-api
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
    networks:
      - app-network
    restart: on-failure

  pendura-ai-client:
    image: jorgeroniel07/pendura-ai-client:0.0.4
    container_name: pendura-ai-cliente
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - pendura-ai-api
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
