ALTER TABLE user_tb ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE user_tb ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE dividas_tb ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE dividas_tb ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();
